### ISSUE TITLE
Published HF model fails to load under transformers >= 5.13 (KeypointModel lacks register_for_auto_class)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/RampNet#19]
## What happened

Loading the published model on a fresh environment (which resolved `transformers 5.14.1`) crashes:

```
  File ".../transformers/models/auto/auto_factory.py", line 383, in from_pretrained
    model_class.register_for_auto_class(auto_class=cls)
AttributeError: type object 'KeypointModel' has no attribute 'register_for_auto_class'
```

Repro: `AutoModel.from_pretrained("projectsidewalk/rampnet-model", trust_remote_code=True)` with `transformers >= 5.13`. The same call works on `5.12.1`, which is the version the sidewalk-auto-labeler now pins as a workaround (found 2026-07-21 while standing up the Richmond/Mapillary deployment on a fresh cluster env).

## Cause (likely)

transformers 5.13 changed the custom-model auto-class API: `from_pretrained` now calls `register_for_auto_class` on the remote-code class, which the HF wrapper's `KeypointModel` (see `scripts/hf_package/modeling_rampnet.py`) doesn't provide — presumably because it doesn't inherit the expected `PreTrainedModel` surface.

## Proposed fix

- Update the HF wrapper to satisfy the current custom-model contract (inherit/shim so `register_for_auto_class` exists), re-export, and verify a round-trip load on both 5.12.x and current transformers.
- State the supported transformers range in the model card so downstream consumers aren't bitten silently.
- Add a small load-smoke test (CI or a documented check) that does `AutoModel.from_pretrained(..., trust_remote_code=True)` against current transformers, so the next API shift is caught at release time rather than in deployments.

**Comment by jonfroehlich** [comment]
Code side landed in PR #28: the exporter now produces a `RampNetModel(PreTrainedModel)` wrapper with `post_init()`, and `tests/test_hf_load.py` verifies `AutoModel.from_pretrained(..., trust_remote_code=True)` loads on both `transformers==5.12.1` and `5.14.1`. The model card documents the supported range.

The remaining step — re-exporting and re-publishing so the **live** `projectsidewalk/rampnet-model` artifact carries the fix (gated on maintainer review) — is split out into #29. This issue can close once #29's push lands and a fresh `from_pretrained` on current `transformers` succeeds.

**Comment by jonfroehlich** [comment]
Resolved — the loading fix now reaches the **live** artifact.

`projectsidewalk/rampnet-model` has been re-exported with the `transformers`-compatible wrapper and re-published (Hub commit `606a1195`).

- **Pre-fix artifact preserved** at tag **`v1.0-paper`** (Hub revision `1078bcd`), so the originally published bytes stay reproducible/citable.
- **Weights byte-identical** to `v1.0-paper` (source checkpoint `epoch_1_step_9378.pth`, sha256 prefix `b0c3ff7a10fc`); only the packaging (`RampNetModel` wrapper, `model_type: rampnet`, proper `auto_map`) and the model card (erratum + supported `transformers` range) changed. The stale bare `modeling.py` was removed in the same commit.
- **Verified:** `AutoModel.from_pretrained("projectsidewalk/rampnet-model", trust_remote_code=True)` now loads and runs a forward pass on **transformers 5.14.1** (output heatmap `(1, 1, 512, 1024)`); the 5.12.1 path stays covered by `tests/test_hf_load.py`.

See #29 for the full re-publish checklist.
